site_name: DataTableBundle
repo_url: https://github.com/kreyu/data-table-bundle

theme:
  name: readthedocs
  hljs_languages:
    - php
    - yaml
    - shell
    - json
    - twig

nav:
  - 'Getting started':
    - 'Installation': 'getting-started/installation.md'
    - 'Usage': 'getting-started/usage.md'
  - 'Reference':
    - 'Columns': 'reference/columns.md'
    - 'Filtration': 'reference/filtration.md'
    - 'Sorting': 'reference/sorting.md'
    - 'Pagination': 'reference/pagination.md'
    - 'Personalization': 'reference/personalization.md'
    - 'Exporting': 'reference/exporting.md'
    - 'Persistence': 'reference/persistence.md'
    - 'Theming': 'reference/theming.md'
    - 'Proxy queries': 'reference/proxy-queries.md'
    - 'Configuration': 'reference/configuration.md'
    - 'Twig': 'reference/twig.md'
  - 'Advanced':
    - 'Integration with Symfony UX Turbo': 'advanced/integration-with-symfony-ux-turbo.md'
    - 'Creating custom request handler': 'advanced/creating-custom-request-handler.md'
    - 'Creating data table type extension': 'advanced/creating-data-table-type-extension.md'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.toc:
      permalink: 
  - pymdownx.superfences

plugins:
  - search
  - badges
  - include-markdown