services:
  _defaults:
    autowire: true
    autoconfigure: true

  Kreyu\Bundle\DataTableBundle\Bridge\Doctrine\Orm\Filter\StringFilter:
    tags:
      - { name: kreyu_data_table.filter }

  Kreyu\Bundle\DataTableBundle\Bridge\Doctrine\Orm\Filter\EntityFilter:
    tags:
      - { name: kreyu_data_table.filter }

  Kreyu\Bundle\DataTableBundle\Bridge\Doctrine\Orm\Filter\NumericFilter:
    tags:
      - { name: kreyu_data_table.filter }

  Kreyu\Bundle\DataTableBundle\Bridge\Doctrine\Orm\Filter\CallbackFilter:
    tags:
      - { name: kreyu_data_table.filter }

  # ---

  Kreyu\Bundle\DataTableBundle\Filter\FilterChain:
    arguments:
      - !tagged_iterator 'kreyu_data_table.filter'

  Kreyu\Bundle\DataTableBundle\Filter\FilterChainInterface: '@Kreyu\Bundle\DataTableBundle\Filter\FilterChain'

  # ---

  Kreyu\Bundle\DataTableBundle\Column\Type\ColumnTypeChain:
    arguments:
      - !tagged_iterator 'kreyu_data_table.column_type'

  # ---

  Kreyu\Bundle\DataTableBundle\Query\Factory\ProxyQueryFactoryChain:
    arguments:
      - !tagged_iterator 'kreyu_data_table.proxy_query_factory'

  Kreyu\Bundle\DataTableBundle\Query\Factory\ProxyQueryFactoryChainInterface: '@Kreyu\Bundle\DataTableBundle\Query\Factory\ProxyQueryFactoryChain'

  Kreyu\Bundle\DataTableBundle\Bridge\Doctrine\Orm\Query\Factory\ProxyQueryFactory: ~

  # ---

  Kreyu\Bundle\DataTableBundle\Type\DataTableTypeChain:
    arguments:
      - !tagged_iterator 'kreyu_data_table.type'

  # ---

  Kreyu\Bundle\DataTableBundle\Factory\DataTableFactory:
    $dataTableTypeChain: '@Kreyu\Bundle\DataTableBundle\Type\DataTableTypeChain'

  Kreyu\Bundle\DataTableBundle\Factory\DataTableFactoryInterface: '@Kreyu\Bundle\DataTableBundle\Factory\DataTableFactory'

  # ---

  Kreyu\Bundle\DataTableBundle\Column\Factory\ColumnFactory: ~
  Kreyu\Bundle\DataTableBundle\Column\Factory\ColumnFactoryInterface: '@Kreyu\Bundle\DataTableBundle\Column\Factory\ColumnFactory'

  Kreyu\Bundle\DataTableBundle\Column\Mapper\Factory\ColumnMapperFactory: ~
  Kreyu\Bundle\DataTableBundle\Column\Mapper\Factory\ColumnMapperFactoryInterface: '@Kreyu\Bundle\DataTableBundle\Column\Mapper\Factory\ColumnMapperFactory'

  Kreyu\Bundle\DataTableBundle\Filter\Factory\FilterFactory: ~
  Kreyu\Bundle\DataTableBundle\Filter\Factory\FilterFactoryInterface: '@Kreyu\Bundle\DataTableBundle\Filter\Factory\FilterFactory'

  Kreyu\Bundle\DataTableBundle\Filter\Mapper\Factory\FilterMapperFactory: ~
  Kreyu\Bundle\DataTableBundle\Filter\Mapper\Factory\FilterMapperFactoryInterface: '@Kreyu\Bundle\DataTableBundle\Filter\Mapper\Factory\FilterMapperFactory'

  Kreyu\Bundle\DataTableBundle\Column\Renderer\HtmlColumnRenderer: ~
  Kreyu\Bundle\DataTableBundle\Column\Renderer\ColumnRendererInterface: '@Kreyu\Bundle\DataTableBundle\Column\Renderer\HtmlColumnRenderer'

  Kreyu\Bundle\DataTableBundle\Column\View\Factory\ColumnHeaderViewFactory: ~
  Kreyu\Bundle\DataTableBundle\Column\View\Factory\ColumnHeaderViewFactoryInterface: '@Kreyu\Bundle\DataTableBundle\Column\View\Factory\ColumnHeaderViewFactory'

  Kreyu\Bundle\DataTableBundle\Column\View\Factory\ColumnValueViewFactory: ~
  Kreyu\Bundle\DataTableBundle\Column\View\Factory\ColumnValueViewFactoryInterface: '@Kreyu\Bundle\DataTableBundle\Column\View\Factory\ColumnValueViewFactory'

  Kreyu\Bundle\DataTableBundle\Column\Type\TextType:
    tags:
      - { name: kreyu_data_table.column_type }

  Kreyu\Bundle\DataTableBundle\Column\Type\LinkType:
    tags:
      - { name: kreyu_data_table.column_type }

  Kreyu\Bundle\DataTableBundle\Column\Type\CollectionType:
    tags:
      - { name: kreyu_data_table.column_type }

  Kreyu\Bundle\DataTableBundle\Column\Type\TemplateType:
    tags:
      - { name: kreyu_data_table.column_type }

  Kreyu\Bundle\DataTableBundle\Column\Type\ActionsType:
    tags:
      - { name: kreyu_data_table.column_type }

  kreyu_data_table.twig.column_renderer_extension:
    class: Kreyu\Bundle\DataTableBundle\Bridge\Twig\ColumnRendererExtension
    tags:
      - twig.extension

  kreyu_data_table.twig.data_table_renderer_extension:
    class: Kreyu\Bundle\DataTableBundle\Bridge\Twig\DataTableRendererExtension
    tags:
      - twig.extension